// GENERATED by scripts/split-archive-fronts.py — do not edit.
//
// Archive flats that have a single-garment front crop under
// /archive-front. Product CARDS use it so the grid shows one
// garment large instead of a front-and-back pair letterboxed
// into a tile; the product PAGE keeps the full flat, where
// seeing both at once is the point.
export const ARCHIVE_FRONTS: ReadonlySet<string> = new Set([
  "fight-or-flight/tees/tee-black-front-hit-only_nnshptzx45.webp",
  "fight-or-flight/tees/tee-red-graffiti-back_nnshptzx47.webp",
  "fight-or-flight/tees/tee-royal-blue-graffiti-back_nnshptzx46.webp",
  "fight-or-flight/tees/tee-white-graffiti-back_nnshptzx48.webp",
  "live-laugh-love/polos/polo-black-pink_nnshptzx14.webp",
  "live-laugh-love/polos/polo-red-white-collar_nnshptzx8.webp",
  "live-laugh-love/polos/polo-white-pink_nnshptzx12.webp",
  "previous-season/jerseys/jersey-classic-pink-orange_shp4.webp",
  "previous-season/jerseys/jersey-classic-red-white_shp5.webp",
  "previous-season/jerseys/jersey-classic-white-pink_shp3.webp",
  "previous-season/jerseys/jersey-urban-black_shp2a.webp",
  "previous-season/jerseys/jersey-urban-blue_shp1a.webp",
  "previous-season/jerseys/jersey-urban-green_shp1b.webp",
  "previous-season/jerseys/jersey-urban-red_shp2b.webp",
  "previous-season/jerseys/jersey-worldwide-black-pink_shpshp2.webp",
  "previous-season/jerseys/jersey-worldwide-white-green_Nshpshp-green.webp",
  "previous-season/jerseys/jersey-worldwide-white-pink_Nshpshp.webp",
  "previous-season/long-sleeve-jerseys/ls-jersey-shoptees-black-blue_shptzBLU.webp",
  "shptz-wrld/polos/polo-black-green-crest_nnshptzx21.webp",
  "shptz-wrld/polos/polo-black-red-seal_nnshptzx11.webp",
  "shptz-wrld/polos/polo-green-black-crest_nnshptzx19.webp",
  "shptz-wrld/polos/polo-red-tonal-crest_nnshptzx20.webp",
  "shptz-wrld/polos/polo-white-green-crest_nnshptzx22.webp",
  "shptz-wrld/polos/polo-white-red-seal_nnshptzx13.webp",
  "trap-house/caps/snapback-black-white_nnshptzx30.webp",
  "trap-house/caps/snapback-blue-white_nnshptzx32.webp",
  "trap-house/caps/snapback-red-white_nnshptzx31.webp",
  "trap-house/hoodies/hoodie-black-blank-back_nnshptzx49.webp",
  "trap-house/hoodies/hoodie-red-graffiti-back_nnshptzx51.webp",
  "trap-house/hoodies/hoodie-white-graffiti-back_nnshptzx52.webp",
  "urban-classic/jerseys/football-jersey-white-maroon_nnshptzx29.webp",
  "urban-classic/polos/polo-black-green-crest_nnshptzx17.webp",
  "urban-classic/polos/polo-black-green-wordmark_nnshptzx18.webp",
  "urban-classic/polos/polo-red-white-wordmark_nnshptzx16.webp",
  "urban-classic/polos/polo-white-green-crest_nnshptzx15.webp",
]);
